# setup travis

language: python

python:
  - 2.6
  - 2.7

services:
  - postgresql

env:
  - DJANGO=1.11.2

before_install:
  - export DJANGO_SETTINGS_MODULE=toomanyflix.settings
  - export PYTHONPATH="/usr/local/lib/python2.7/dist-packages"
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test
